import React from 'react';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import Hero from '../components/Hero';
import { Shield, Lock, Eye, FileText } from 'lucide-react';
import SEO from '../components/SEO';

const PrivacyPolicy: React.FC = () => {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="min-h-screen bg-slate-50 dark:bg-transparent pb-24"
    >
      <SEO 
        title="Privacy Policy | Oberon Services — GDPR & CCPA Compliant"
        description="Oberon Services Privacy Policy: how we collect, protect, and retain your security telemetry data. Fully compliant with GDPR, CCPA, and NIST 800-88 data destruction standards."
        canonical="https://www.oberon-services.com/privacy"
        schema={[
          {
            "@context": "https://schema.org",
            "@type": "WebPage",
            "name": "Privacy Policy — Oberon Services",
            "url": "https://www.oberon-services.com/privacy",
            "description": "Oberon Services Privacy Policy covering data collection, retention, security controls, and client rights under GDPR and CCPA.",
            "publisher": {
              "@type": "Organization",
              "@id": "https://www.oberon-services.com/#organization",
              "name": "Oberon Services",
              "logo": "https://www.oberon-services.com/logo-dark.png"
            }
          },
          {
            "@context": "https://schema.org",
            "@type": "SpecialAnnouncement",
            "@id": "https://www.oberon-services.com/privacy#legal",
            "name": "Privacy Policy",
            "text": "Oberon Services Privacy Policy governing the collection, use, and protection of client data in the delivery of Managed Security Services.",
            "datePosted": "2023-10-24",
            "expires": "2099-12-31",
            "announcementLocation": {
              "@type": "LocalBusiness",
              "@id": "https://www.oberon-services.com/#organization",
              "name": "Oberon Services"
            }
          }
        ]}
      />
      <Hero 
        title="Privacy Policy" 
        subtitle="Your trust is our perimeter. We protect your data with the same rigor we apply to your infrastructure."
        backgroundImage="https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80"
      />

      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <div className="bg-white dark:bg-slate-900 rounded-2xl p-8 md:p-12 border border-slate-200 dark:border-slate-800 shadow-xl shadow-slate-200/50 dark:shadow-none">
          
          <div className="prose prose-slate dark:prose-invert max-w-none">
            <p className="text-sm text-slate-500 uppercase tracking-widest font-bold mb-8">Last Updated: October 24, 2023</p>

            <h2>1. Introduction</h2>
            <p>
              Oberon Services ("we," "our," or "us") is committed to protecting the privacy and security of your information. As a Managed Security Service Provider (MSSP), we handle sensitive data regarding your infrastructure, security posture, and employees. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website or engage our services.
            </p>

            <h2>2. Information We Collect</h2>
            <p>We collect information in the following categories to provide our security services:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Client Data:</strong> Information provided by you for the provision of services, including network diagrams, IP addresses, system configurations, and employee contact details.</li>
              <li><strong>Security Telemetry:</strong> Logs, events, flow data, and alerts generated by your systems (endpoints, firewalls, cloud environments) that are ingested into our SOC/SIEM for monitoring.</li>
              <li><strong>Contact Information:</strong> Names, email addresses, and phone numbers of your authorized points of contact.</li>
            </ul>

            <h2>3. How We Use Your Information</h2>
            <p>We use your data strictly for the purpose of delivering security outcomes:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Threat Detection:</strong> Analyzing telemetry to identify and respond to security incidents.</li>
              <li><strong>Forensics:</strong> Investigating the root cause of alerts or breaches.</li>
              <li><strong>Communication:</strong> Sending security alerts, reports, and service updates to your designated team.</li>
              <li><strong>Compliance:</strong> Generating audit reports (e.g., PCI, HIPAA, SOC 2) as requested by you.</li>
            </ul>

            <h2>4. Data Retention & Security</h2>
            <p>
              We implement industry-standard encryption (AES-256) for data at rest and TLS 1.3 for data in transit. 
            </p>
            <p>
              <strong>Log Retention:</strong> Security logs are retained based on your service tier (Hot: 30-90 days, Cold: up to 7 years). Upon contract termination, data is securely destroyed in accordance with NIST 800-88 standards.
            </p>

            <h2>5. Sharing of Information</h2>
            <p>We do not sell your data. We may share information only in the following circumstances:</p>
            <ul>
              <li><strong>Sub-processors:</strong> With trusted vendors (e.g., cloud providers like AWS/Azure) necessary to deliver our infrastructure, under strict Data Processing Agreements (DPA).</li>
              <li><strong>Legal Requirements:</strong> If required by law enforcement or a valid court order, though we pledge to challenge overbroad requests to protect client confidentiality.</li>
            </ul>

            <h2>6. Your Rights</h2>
            <p>
              Depending on your jurisdiction (GDPR, CCPA), you may have rights regarding your personal data, including access, correction, and deletion. Please note that certain security logs may be immutable for audit integrity purposes.
            </p>

            <h2>7. Contact Us</h2>
            <p>
              If you have questions about this policy or our data practices, please contact our Data Protection Officer (DPO) at:
              <br />
              <a href="mailto:security@oberon-services.com" className="text-brand-accent hover:underline">security@oberon-services.com</a>
            </p>
            
            <div className="mt-12 pt-6 border-t border-slate-200 dark:border-slate-800 flex flex-wrap gap-4 justify-between items-center">
              <Link to="/" className="text-brand-accent hover:underline font-bold text-sm flex items-center gap-1">
                ← Back to Homepage
              </Link>
              <Link to="/contact" className="px-5 py-2.5 bg-slate-100 dark:bg-slate-800 text-slate-800 dark:text-slate-200 hover:bg-slate-200 dark:hover:bg-slate-700 hover:text-brand-accent dark:hover:text-brand-accent rounded-lg text-sm font-semibold transition-all">
                Contact Security Team
              </Link>
            </div>
          </div>
        </div>
      </div>
    </motion.div>
  );
};

export default PrivacyPolicy;